[package]
name = "R9A02G021"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.0", optional = true }
vcell = "0.1.0"


[features]
rt = []

[package.metadata.docs.rs]
features = ["rt", "critical-section"]
