[package]
name = "FrenoEmergencia"
version = "0.1.0"
edition = "2021"


[dependencies]
critical-section = { version = "1.2.0" }
R9A02G021 = {path = "../R9A02G021", features = ["rt"]} 
riscv = { version = "0.12.1" }
riscv-peripheral = "0.2.0"
riscv-rt = { version = "0.13.0"}
panic-halt = "1.0.0"

