
MEMORY
{
    FLASH : ORIGIN = 0x00000000, LENGTH = 128K
    SRAM : ORIGIN = 0x20004000, LENGTH = 12K
}

INCLUDE device.x

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", SRAM);
REGION_ALIAS("REGION_BSS", SRAM);
REGION_ALIAS("REGION_HEAP", SRAM);
REGION_ALIAS("REGION_STACK", SRAM);

INCLUDE link.x