// Automatically generated by emmtrix Code Generator (Apr 20 2021 07:25:46)
// Do not edit this file manually. Any changes will be overwritten without confirmation.
// Installation: /srv/www/codegen.service.emmtrix.com/install/20220429
// Command Line Arguments: _scenario.sce --makefile=gnumake --report-includefiles=1
// Output Language: C99 (ISO/IEC 9899:1999)

#include <math.h>
#include <stdbool.h>
#include <stdint.h>

#include "emx_codegen.h"

#include "_frenoEmergencia.h"


void _frenoEmergencia(double * const y1_data, double u1_data) {
  int32_t tmp4_data, tmp5_data, tmp6_data; 
  
  // _scenario.sce(16:13-49):  emx_func_file('_frenoEmergencia.c')
  // _scenario.sce(37:5-30):  tmp4 = double(u1 > tmp2);
  tmp4_data = (int32_t )((u1_data > 10.0)); 
  
  // _scenario.sce(43:5-30):  tmp5 = double(u1 < tmp3);
  tmp5_data = (int32_t )((u1_data < 20.0)); 
  
  // _scenario.sce(49:5-32):  tmp6 = double(tmp4 & tmp5);
  tmp6_data = (int32_t )(((bool )(tmp4_data) && (bool )(tmp5_data))); 
  
  // _scenario.sce(55:5-15):  y1 = tmp6;
  *y1_data = (double )(tmp6_data); 
} 
