/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : r9a02g021_fromScilab.c
*  Description  : Main Program
*  Creation Date: 2024-11-26
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

//includes añadidos
#include "r_cg_interrupt_handlers.h"
#include "r_cg_uarta_common.h"
#include "r_cg_uarta.h"
#include "r_smc_interrupt.h"
#include "r_cg_icu.h"
#include "Pin.h"
#include "_frenoEmergencia.h"



MD_STATUS g_uarta1_tx_end = 0U;     /* uartA1 transmission end */
volatile const uint8_t message[10] = {"FRENO OK "};    /* Mensaje de freno ok */

volatile uint32_t blinkDelay = 500; // Initial blink delay of 0.5 second
extern volatile int boton;

volatile double speed = 0;
double emergencyBreak;
volatile int blink = 0;

int main(void);

int main(void)
{
    /* Start SW Interrupt */
    R_Config_ICU_IRQ4_Start();

    /* Start UART */
    R_Config_UARTA1_Start();

    while(1)
    {
    	if (boton == 1){
    		speed = 15;  //dentro del rango mayor 10 y menor a 20 ENTONCES PARPADEO LED
    		blink = 1;
    	}
    	else if (boton == 0){
    		speed = 30; //fuera del rango mayor 10 y menor a 20 ENTONCES ENVIA MENSAJE FRENO OK
    		blink = 0;
    	}

    	_frenoEmergencia(&emergencyBreak, speed);

    	if((emergencyBreak != 0.0) && (blink == 1)){ //dentro del rango
    		PIN_WRITE(LED1) = ~PIN_READ(LED1); //Parpadeo LED
    		R_BSP_SoftwareDelay(blinkDelay, BSP_DELAY_MILLISECS);
    	}
    	else{
    		PIN_WRITE(LED1) = 0;
    		R_BSP_SoftwareDelay(1000, BSP_DELAY_MILLISECS); // DELAY 1s
    		g_uarta1_tx_end = R_Config_UARTA1_Send((uint8_t *)message, sizeof(message));
    	}
    }
    R_Config_ICU_IRQ4_Stop();
    return 0;
}





